Feature/add logging and rolling appender support
nvseshaiah2013/hisaab_kitaab_api_spring pull request #24
Opened 2024-02-10 16:00 UTC by rahul-ojha-07

2024-02-10 16:59 UTC, nvseshaiah2013 requested changes

2024-02-10 16:59 UTC, nvseshaiah2013 commented on pom.xml
> +		<dependency>
Why is this dependency required ?

2024-02-11 04:32 UTC, rahul-ojha-07 commented on pom.xml
> +		<dependency>
removed

2024-02-11 04:32 UTC, nvseshaiah2013 approved these changes

2024-02-11 04:32 UTC, merged