added custom exception handler
nvseshaiah2013/hisaab_kitaab_api_spring pull request #34
Opened 2024-02-15 18:17 UTC by samir937

![image](https://github.com/nvseshaiah2013/hisaab_kitaab_api_spring/assets/38258560/838a84c2-e0a0-4183-8722-a7b1ec3e893b)

2024-02-15 18:18 UTC, samir937 commented on src/main/java/com/kitaab/hisaab/ledger/exception/CustomExceptionHandler.java
> +        ErrorResponse message = new ErrorResponse(new Date(), ex.getMessage(), ApplicationConstants.USERNAME_NOT_FOUND,
errorCode & errorMessage can be replaceable , after user api pull merge

2024-02-16 14:44 UTC, nvseshaiah2013 requested changes

2024-02-16 14:44 UTC, nvseshaiah2013 commented on src/main/java/com/kitaab/hisaab/ledger/exception/CustomExceptionHandler.java
> +        ErrorResponse message = new ErrorResponse(new Date(), ex.getMessage(), ApplicationConstants.DEFAULT_ERROR_CODE,
ApplicationConstants.DEFAULT_ERROR_CODE not defined in the ApplicationConstants

2024-02-16 14:44 UTC, nvseshaiah2013 commented on src/main/java/com/kitaab/hisaab/ledger/exception/CustomExceptionHandler.java
> +        ErrorResponse message = new ErrorResponse(new Date(), ex.getMessage(), ApplicationConstants.DEFAULT_ERROR_CODE,
ApplicationConstants.DEFAULT_ERROR_CODE not defined in the ApplicationConstants

2024-02-17 08:15 UTC, nvseshaiah2013 approved these changes

2024-02-17 08:15 UTC, merged